business_card_project/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),



]

business_card_project/business_card/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from portfolio import views as portfolio_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', portfolio_views.home, name='home'),
    path('about/',portfolio_views.about_me, name='about'),
    path('skills/',portfolio_views.skills, name='skills'),
    path('projects/',portfolio_views.projects, name='projects'),
    path('blog/', include('blog.urls')),
    path('contact/',portfolio_views.contact_form, name='contact'),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

business_card_project/blog/models.py
from django.db import models

# Create your models here.

class BlogArticles(models.Model):
    title = models.CharField(max_length=200)
    date = models.DateField()
    description = models.TextField(max_length=300)

    def __str__(self):
        return self.title

business_card_project/portfolio/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)
    stack = models.TextField()

    def __str__(self):
        return self.title

class Skills(models.Model):
    skill = models.CharField(max_length=200)

    def __str__(self):
        return self.skill

business_card_project/portfolio/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(max_length=20, required=True, label='name', widget=forms.TextInput(attrs={'class':'form-field-control-above', 'placeholder':'Name'}))
    email = forms.EmailField(required=True, label='email', widget=forms.TextInput(attrs={'class':'form-field-control-above', 'placeholder':'Email'}))
    subject = forms.CharField(max_length=100, required=True, label='subject', widget=forms.TextInput(attrs={'class':'form-field-control-above','placeholder':'Subject'}))
    message = forms.CharField(widget=forms.Textarea(attrs={'class':'form-field-control-below','placeholder':'Your message...'}), required=True, label='message')

business_card_project/blog/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from .models import BlogArticles

# Create your views here.

def all_blogs(request):
    #order by date (descending), limit to the last 5 in a main blog site
    blog_articles = BlogArticles.objects.order_by('-date')
    content = {
        'articles' : blog_articles
    }
    return render(request,'blog/all_blogs.html', content)

def detail(request, blog_id):
    blog = get_object_or_404(BlogArticles, pk=blog_id)
    content = {
        'blog':blog
    }
    return render(request,'blog/detail.html', content)

business_card_project/portfolio/views.py
from django.shortcuts import render
from .models import Project
from .models import Skills
from .forms import ContactForm
from django.core.mail import send_mail, BadHeaderError
from decouple import config
# Create your views here.


def home(request):
    return render(request,'portfolio/home.html')

def about_me(request):
    return render(request,'portfolio/aboutme.html')

def skills(request):
    my_skill = Skills.objects.all()
    content = {
        'my_skill' : my_skill,
    }
    return render(request,'portfolio/skills.html', content)

def projects(request):
    projects = Project.objects.all()
    content = {
        'projects':projects
    }
    return render(request,'portfolio/projects.html', content)

def contact_form(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            admin_address = config('admin_address')
            responder_address = config('responder_address')
            client_address = request.POST['email']
            message_for_admin = f"""
            name: {request.POST['name']}
            email: {request.POST['email']}
            message: {request.POST['message']}
            """
            message_for_client = f"""
            Thank you {request.POST['name'].capitalize()} for your message - I will answer to your question as soon as possible.
            Have a nice day! :)
            Tomasz Pasternak
             
            --- message generated automatically --- please do not reply to this email ---
            """
            try:
                send_mail(request.POST['subject'], message_for_admin, responder_address,[admin_address])
                send_mail(request.POST['subject'], message_for_client, responder_address,[client_address])
            except BadHeaderError:
                print('-----incorrect header-----')
            form = ContactForm()


    else:
        form = ContactForm()

    info = "Message sent - thank you!"
    content = {
        'form': form,
        'info': info,
    }
    return render(request,'portfolio/contact_form.html',content)

business_card_project/blog/templates/blog/all_blogs.html
{% extends 'portfolio/base.html' %}

{% block content %}
    <h1>Really awesome stuff</h1>
    <h2>in this section Tomek has written {{ articles.count }} article{{ articles.count|pluralize }}</h2>
    {% for article in articles %}
    <a href="{% url 'blog:detail' article.id %}"><h1>{{article.title}}</h1></a>
    <p>{{article.date|date:'M d Y'}}</p>
    <h3>{{article.description|truncatechars:100}}</h3><br>
    {% endfor %}
{% endblock %}

business_card_project/blog/templates/blog/detail.html
{% extends 'portfolio/base.html' %}

{% block content %}
    <h1>{{blog.title}}</h1>
    <h2> .: {{ blog.date|date:'F jS Y' }} :.</h2>
    {{ blog.description|safe }}
{% endblock%}

business_card_project/portfolio/templates/portfolio/aboutme.html
{% extends 'portfolio/base.html' %}
{% load static %}

{% block content %}
 <!--AboutMe Section-->
        <section class="about section">
          <div class="container">
            <div class="row">
              <div class="section-title">
                <h2>About Me</h2>
              </div>
            </div>
              <div class="row">
                  <div class="about-content">
                      <div class="row">
                          <div class="about-text">
                              <h3>I am Tomasz Pasternak and <span>Python Freelancer</span></h3>
                              <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit,
                                  sed do eiusmod tempor incididunt ut labore et dolore
                                  magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
                                  ullamco laboris nisi ut aliquip ex ea commodo consequat.
                                  Duis aute irure dolor in reprehenderit in voluptate velit esse
                                  cillum dolore eu fugiat nulla pariatur.
                              </p>
                          </div>
                      </div>
                      <div class="row">
                          <div class="personal-info">
                              <div class="row">
                                  <div class="info-item">
                                      <p>Location : <span>Cracow / Remote</span></p>
                                  </div>
                                  <div class="info-item">
                                      <p>University : <span>AGH University of Science and Technology</span></p>
                                  </div>
                                  <div class="info-item">
                                      <p>Degree : <span>Automation and Robotics Engineer</span></p>
                                  </div>
                                  <div class="info-item">
                                      <p>Hobby : <span>Programming, Football, Formula One, Workout, Cars</span></p>
                                  </div>
                              </div>
                          </div>
                          <div class="skills">
                              <div class="button-show-skills" >
                                  <a href="{% url 'skills'%}" class="btn" >Show Skills</a>

                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
        </section>
        <!--AboutMe Section End-->
{% endblock %}

business_card_project/portfolio/templates/portfolio/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'portfolio/loading.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/custom.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/skins/havefun.css' %}">

    <link rel="apple-touch-icon" sizes="180x180" href="{% static "portfolio/logo/favicon_io/apple-touch-icon.png" %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static "portfolio/logo/favicon_io/favicon-32x32.png" %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static "portfolio/logo/favicon_io/favicon-16x16.png" %}">
    <link rel="manifest" href="{% static "portfolio/logo/favicon_io//site.webmanifest" %}">


    <title>Python developer!</title>
  </head>
  <body>

    <!--  Main container-->
    <div class="main-container">
    <!--Sticky Navbar-->
        <header>
<!--            <a href="#" class="logo">LOGO</a>-->
            <ul>
                <li><a href="{% url 'home' %}" class="active"><i class="fa fa-home"></i> Home</a> </li>
                <li><a href="{% url 'about' %}"><i class="fa fa-user"></i> About me</a> </li>
                <li><a href="{% url 'projects' %}"><i class="fa fa-briefcase"></i> Projects</a> </li>
                <li><a href="#"><i class="fa fa-book"></i> Blog</a> </li>
                <li><a href="{% url 'contact' %}"><i class="fa fa-comments"></i> Contact</a> </li>
            </ul>
        </header>
    <!--Sticky Navbar End-->

    <!-- Mobile Hamburger -->

        <nav role="navigation">
          <div id="menuToggle">
            <!--
            A fake / hidden checkbox is used as click receiver,
            so you can use the :checked selector on it.
            -->
            <input type="checkbox" />

            <!--
            Some spans to act as a hamburger.
            -->
            <span></span>
            <span></span>
            <span></span>


            <ul id="menu">
                <a href="{% url 'home' %}"><li>Home</li></a>
                <a href="{% url 'about' %}"><li>About Me</li></a>
                <a href="{% url 'projects' %}"><li>Projects</li></a>
                <a href="#"><li>Blog</li></a>
                <a href="{% url 'contact' %}"><li>Contact</li></a>
                <a href="https://www.linkedin.com/in/tomasz-pasternak-pth-at-rb/" target="_blank"><li>Linkedin</li></a>
            </ul>
          </div>
        </nav>

    <!-- Mobile Hamburger End -->


      <!--  Main content-->
      <div class="main-content">
        {% block content %}


        {% endblock %}
      </div>
      <!--  Main content end-->
    </div>
  <!--  Main container end-->


  </body>
</html>

business_card_project/portfolio/templates/portfolio/contact_form.html
{% extends 'portfolio/base.html' %}

{% block content %}
<!--ContactForm Section-->
 <section class="about section">
          <div class="container">
            <div class="row">
              <div class="section-title">
                <h2>Contact Me</h2>
              </div>
            </div>
              <div class="row">
                  <div class="about-content">
                      <div class="row">
                          <div class="about-text">
                              <h3>I will reply to your message as soon as possible </h3>
                          </div>
                      </div>
                  </div>
              </div>
                <!--Form -->
              <div class="row">
                  <!--contact-info-item-->
                  <div class="contact-info-item">
                      <div class="icon"><i class="fa fa-envelope"></i> </div>
                      <h4>Email</h4>
<!--                      <p>t.pasternak94@gmail.com</p>-->
                  </div>
                  <!--contact-info-item end-->

                  <div class="container-form">
                      <div class="row">
                          <form class="contact-form" method="post">
                            {% csrf_token %}
                              <div class="row">
                                <div class="form-item-above">
                                    <div class="form-group">
                                        {{ form.name }}
                                    </div>
                                </div>
                                <div class="form-item-above">
                                    <div class="form-group">
                                        {{ form.email }}
                                    </div>
                                </div>
                              </div>
                              <div class="row">
                                <div class="form-item-above">
                                    <div class="form-group">
                                        {{ form.subject }}
                                    </div>
                                </div>
                              </div>
                              <div class="row">
                                  <div class="form-item-below">
                                    <div class="form-group">
                                        {{ form.message }}
                                    </div>
                                </div>
                              </div>
                              <div class="submit_raw">
                                  <button type="submit" class="btn-form">Send Message</button>
                              </div>
                          </form>
                      </div>
                  </div>

                <!--Form End-->
              </div>
          </div>
 </section>
<!--ContactForm Section End-->
{% endblock %}

business_card_project/portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}
{% load static %}

{% block content %}
        <!--Home Section-->
    <section class="banner">
<!--        loop muted-->
        <video class="magic_intro" autoplay muted>
            <source src="{% static 'portfolio/intro/magic_effect.mp4' %}" type="video/mp4">
        </video>
        <h1>
            <span>T</span>
            <span>.</span>
            <span>P</span>
            <span>A</span>
            <span>S</span>
            <span>T</span>
            <span>E</span>
            <span>R</span>
            <span>N</span>
            <span>A</span>
            <span>K</span>
            <span>&#xA0;</span>
            <span>&trade;</span>
        </h1>
    </section>
        <section class="home-section">
          <div class="container">
            <div class="intro">
                    <h1 class="flashit" >Python Developer</h1>
                    <div class="social-media">
                      <a class='near' href="#" class="near ld ld-heartbeat"></a>
                      <a class='center' href="https://www.linkedin.com/in/tomasz-pasternak-pth-at-rb/" target="_blank" class="ln-blue"><i class="fa fa-linkedin-square"></i> </a>
                      <a class='near' href="#" class="near ld ld-heartbeat"> </a>
                    </div>
            </div>
          </div>
        </section>
        <!--Home Section End-->
<!--        &lt;!&ndash;AboutMe Section&ndash;&gt;-->
<!--        <section class="about section">-->
<!--          <div class="container">-->
<!--            <div class="row">-->
<!--              <div class="section-title">-->
<!--                <h2>About Me</h2>-->
<!--              </div>-->
<!--            </div>-->
<!--              <div class="row">-->
<!--                  <div class="about-content">-->
<!--                      <div class="row">-->
<!--                          <div class="about-text">-->
<!--                              <h3>I am Tomasz Pasternak and <span>Python Freelancer</span></h3>-->
<!--                              <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit,-->
<!--                                  sed do eiusmod tempor incididunt ut labore et dolore-->
<!--                                  magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation-->
<!--                                  ullamco laboris nisi ut aliquip ex ea commodo consequat.-->
<!--                                  Duis aute irure dolor in reprehenderit in voluptate velit esse-->
<!--                                  cillum dolore eu fugiat nulla pariatur.-->
<!--                              </p>-->
<!--                          </div>-->
<!--                      </div>-->
<!--                      <div class="row">-->
<!--                          <div class="personal-info">-->
<!--                              <div class="row">-->
<!--                                  <div class="info-item">-->
<!--                                      <p>Location : <span>Cracow / Remote</span></p>-->
<!--                                  </div>-->
<!--                                  <div class="info-item">-->
<!--                                      <p>University : <span>AGH University of Science and Technology</span></p>-->
<!--                                  </div>-->
<!--                                  <div class="info-item">-->
<!--                                      <p>Degree : <span>Automation and Robotics Engineer</span></p>-->
<!--                                  </div>-->
<!--                                  <div class="info-item">-->
<!--                                      <p>Hobby : <span>Programming, Football, Formula One, Workout, Cars</span></p>-->
<!--                                  </div>-->
<!--                              </div>-->
<!--                          </div>-->
<!--                          <div class="skills">-->
<!--                              <div class="button-show-skills" >-->
<!--                                  <a href="{% url 'skills'%}" class="btn" >Show Skills</a>-->
<!--                              </div>-->
<!--                          </div>-->
<!--                      </div>-->
<!--                  </div>-->
<!--              </div>-->
<!--          </div>-->
<!--        </section>-->
<!--        &lt;!&ndash;AboutMe Section End&ndash;&gt;-->
{% endblock %}

business_card_project/portfolio/templates/portfolio/projects.html
{% extends 'portfolio/base.html' %}

{% block content %}
<!--Projects Section-->
 <section class="about section">
          <div class="container">
            <div class="row">
              <div class="section-title">
                <h2>Projects</h2>
              </div>
            </div>
              <div class="row">
                  <div class="about-content">
                      <div class="row">
                          <div class="about-text">
                              <h3>Lorem ipsum dolor </h3>
                              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit,
                                  sed do eiusmod tempor incididunt ut labore et dolore</p>
                          </div>
                      </div>
                  </div>
              </div>
              <div class="row">
                <!--Project Item-->
                  <div class="project-item">
                      {% for project in projects %}
                      <div class="project-item-inner">
                          <img class="project-img" src="{{ project.image.url }}" alt="project" width="250" height="200">
                          <div class="overlay_project">{{ project.stack }}</div>
                          <h4 class="project-title">{{ project.title }}</h4>
                          <p>{{ project.description }}</p>
                      </div>
                      {% endfor %}
                  </div>
                <!--Project Item End-->
              </div>
          </div>
        </section>
<!--Projects Section End-->
{% endblock %}

business_card_project/portfolio/templates/portfolio/skills.html
{% extends 'portfolio/base.html' %}

{% load static %}

{% block content %}
 <!--Skills Site Section-->
        <section class="about section">
          <div class="container">
            <div class="row">
              <div class="section-title">
                <h2>What I Use?</h2>
              </div>
            </div>
              <div class="row">
                  <div class="about-content">
                       <div class="row">
                          <div class="skills-text">
                              <p>"Science is magic that works" ― Kurt Vonnegut</p>
                          </div>
                      </div>

                      <div class="row">
                          <div class="skills-container-animation">
                              <div class="line-show-skills-above" >
                                  <p class="line_above ld ld-damage" style="animation-duration:8s"></p>
                              </div>
                          </div>
                          <div class="skill-info">
                              <div class="row">
                                  <div class="skill-item">
                                      {% for tech in my_skill %}
                                      <p class="my_skills">{{ tech }}</p>
                                      {% endfor %}
                                  </div>
                              </div>
                          </div>
                          <div class="skills-container-animation">
                              <div class="line-show-skills-below" >
                                  <p class="line_below ld ld-damage" style="animation-duration:8s"></p>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
        </section>
        <!--Skills Site Section End-->
{% endblock %}